add solution
dmitrikll/JP05-Inheritance pull request #1
Opened 2024-02-11 20:18 UTC by dmitrikll

2024-02-12 20:57 UTC, pipekalo requested changes

2024-02-12 20:57 UTC, pipekalo commented on src/Animals.java
> +public class Animals {
Class? May be interface? Only methods here

2024-02-12 20:57 UTC, pipekalo commented on src/Main.java
> +    public static void main(String[] args) {
в принципе тут можешь этого не делать

2024-02-13 17:37 UTC, dmitrikll commented on src/Animals.java
> +public class Animals {
refactored the interface

2024-02-13 20:56 UTC, pipekalo approved these changes

2024-02-14 17:57 UTC, merged